apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - canary.yaml
  - nginx-ingress.yaml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

