apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview-apps

spec:
  generators:
    - pullRequest:
        # Short requeue time so we don't have to set up a webhook.
        requeueAfterSeconds: 15
        github:
          owner: anusha-ragunathan # Replace this with your GitHub username.
          repo: ArgoCDRollouts
          labels:
            - preview
          tokenRef:
            secretName: github-token
            key: token
  template:
    metadata:
      name: "{{number}}-preview"
    spec:
      project: "appset"
      source:
        # Feel free to change crenshaw-dev to your own username. The manifests should be identical, since you just forked
        # the repo.
        repoURL: "https://github.com/anusha-ragunathan/ArgoCDRollouts"
        targetRevision: "{{branch}}"
        path: "manifests/ArgoCD201-ApplicationSets/example-app"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "default"
      syncPolicy:
        automated: {}
